[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
events_manager = "FaVJjaBbAR5nQvXmkLkVRKxf5B1TXFRDSh6Be7vwN95s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/matuu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
